import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Provider from "@/utils/Provider";
import Sidebar from "@/components/Sidebar/Sidebar";
import 'react-datepicker/dist/react-datepicker.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <Navbar /> {/* Navbar siempre arriba */}

          {/* Quitar mx-auto para que no haya margen a la izquierda */}
          <div className="flex pt-16 min-h-screen max-w-full">
            <Sidebar />
            <main className="flex-1 p-6 bg-[#f2f2f2] dark:bg-[#201f1f]">
              {children}
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}